@WebApi2026_HostAddress = https://localhost:7002

GET {{WebApi2026_HostAddress}}/api/weatherforecast/
Accept: application/json


###

@id=1
GET {{WebApi2026_HostAddress}}/api/weatherforecast/{{id}}

###
